language: php
cache: composer
env:
  - VIRTUALHOST_NAME=pricewaiter.travis PROTOCOL=http

addons:
  hosts:
    - pricewaiter.travis

before_install:
  - composer self-update
  - script/install-packages.sh

install:
  - composer install

before_script:
  - script/configure-webserver.sh
  - script/install-magerun.sh
  - script/install-modman.sh
  - script/install-magento.sh
  - script/run-modman.sh

script:
  - script/build-and-test.sh

after_success:
  - vendor/bin/coveralls

after_script:
  - sudo cat /var/log/nginx/access.log

after_failure:
  - sudo cat /var/log/nginx/error.log
