language: php
cache: composer
env:
  - VIRTUALHOST_NAME=pricewaiter.travis

addons:
  hosts:
    - pricewaiter.travis

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libxml2 libxml2-utils
  - composer self-update

install:
  - composer install

before_script:
  - script/install-webserver.sh
  - script/install-magerun.sh
  - script/install-modman.sh
  - script/install-magento.sh
  - script/run-modman.sh

script:
  - php make.php clean --ansi
  - php make.php check --ansi
  - php make.php build --ansi

after_script:
  - vendor/bin/phpunit
  - vendor/bin/coveralls
