mysql:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=password

order_verifier:
    build: docker/order_verifier

phpmyadmin:
    build: docker/phpmyadmin
    ports:
        - "7777:80"
    links:
        - mysql

v19php55:
  build: .
  dockerfile: ./docker/v1.9-php5.5/Dockerfile
  environment:
    - MAGENTO_DB_PASSWORD=password
    - MAGENTO_DB_USER=root
    # Use these variables to link into your PriceWaiter docker environment running locally.
    - PRICEWAITER_API_URL=http://dockerhost:8008
    - PRICEWAITER_RETAILER_URL=http://localhost:8009
    - PRICEWAITER_WIDGET_URL=http://dockerhost:8006
    # Comment this line out if you want to use "real" order verification via PRICEWAITER_API_URL
    - PRICEWAITER_ORDER_VERIFICATION_URL=http://order_verifier/1/order/verify
  extra_hosts:
    # Important: Tell tests how to find magento host internally.
    - "magento:127.0.0.1"
    # Uncomment to enable talking to a PW instance running on "dockerhost" urls.
    # Replace IP with the output of `docker-machine ip dev` or equivalent.
    # - "dockerhost:192.168.99.100"
  links:
    - mysql
    - order_verifier
  ports:
    - "1955:1955"
  volumes:
    - ./app:/var/www/htdocs/.modman/pricewaiter/app
    - ./build:/var/www/htdocs/.modman/pricewaiter/build
    - ./js:/var/www/htdocs/.modman/pricewaiter/js
    - ./package.template.xml:/var/www/htdocs/.modman/pricewaiter/package.template.xml
    - ./skin:/var/www/htdocs/.modman/pricewaiter/skin
    - ./tests:/var/www/htdocs/.modman/pricewaiter/tests
    # Download source into lib/magento-1.9 and uncomment these to volume it in.
    - ./lib/magento-1.9/app/code/core:/var/www/htdocs/app/code/core
    - ./lib/magento-1.9/lib:/var/www/htdocs/lib

v19php55-tests:
    build: .
    dockerfile: ./docker/functional-tests/Dockerfile
    links:
        - "v19php55:magento"
    environment:
        - MAGENTO_BASE_URL=http://magento:1955
        - PRICEWAITER_API_KEY=MAGENTO
        - PRICEWAITER_SHARED_SECRET=SECRET
    volumes:
        - ./tests/functional/datasets:/usr/src/datasets
        - ./tests/functional/tests:/usr/src/tests
    # NOTE: bin/run-functional-tests uses this container, but it is not required for normal Magento usage.
    #       If you know of a better way to have this container in the docker-compose.yml but
    #       not automatically bring it up, feel free to modify.
    command: "sh -c 'echo This is a run-only container. It will just stay up to avoid bringing down other containers.;while (true); do sleep 1; done;'"
