mysql:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=password

order_verifier:
    build: docker/order_verifier

phpmyadmin:
    build: docker/phpmyadmin
    ports:
        - "7777:80"
    links:
        - mysql

v19php55:
  build: .
  dockerfile: ./docker/v1.9-php5.5/Dockerfile
  environment:
    - MAGENTO_DB_PASSWORD=password
    - MAGENTO_DB_USER=root
    # Use these variables to link into your PriceWaiter docker environment running locally.
    - PRICEWAITER_API_URL=http://dockerhost:8008
    - PRICEWAITER_RETAILER_URL=http://localhost:8009
    - PRICEWAITER_WIDGET_URL=http://dockerhost:8006
    # Comment this line out if you want to use "real" order verification via PRICEWAITER_API_URL
    - PRICEWAITER_ORDER_VERIFICATION_URL=http://order_verifier/1/order/verify
  extra_hosts:
    # Important: Tell tests how to find magento host internally.
    - "magento:127.0.0.1"
    # Uncomment to enable talking to a PW instance running on "dockerhost" urls.
    # Replace IP with the output of `docker-machine ip dev` or equivalent.
    # - "dockerhost:192.168.99.100"
  links:
    - mysql
    - order_verifier
  ports:
    - "1955:1955"
  volumes:
    - ./app:/var/www/htdocs/.modman/pricewaiter/app
    - ./js:/var/www/htdocs/.modman/pricewaiter/js
    - ./skin:/var/www/htdocs/.modman/pricewaiter/skin
    - ./tests:/var/www/htdocs/.modman/pricewaiter/tests
    # Download source into lib/magento-1.9 and uncomment these to volume it in.
    # - ./lib/magento-1.9/app/code/core:/var/www/htdocs/app/code/core
    # - ./lib/magento-1.9/lib:/var/www/htdocs/lib

