<?php
/*
 * Copyright 2013 Price Waiter, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
?>
<?php $_product = Mage::registry('current_product'); ?>
<?php if($_product->isSaleable()): ?>
<?php
$helper = $this->_getHelper();
if ($helper->isEnabled()):
?>
<script type="text/javascript">
//<![CDATA[
<?php echo $helper->getPriceWaiterOptions(); ?>
<?php echo $helper->getProductOptions(); ?>
var PriceWaiterWidgetUrl = "<?php echo $helper->getWidgetUrl(); ?>";
//]]>
</script>
<div class="name-your-price-widget" style='display: block; clear: both; padding-top: 10px;'>
    <span id="pricewaiter"></span>
</div>
<?php endif; ?>
<?php endif; ?>
