<?php
/*
 * Copyright 2013-2014 Price Waiter, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
?>
<?php $_product = Mage::registry('current_product'); ?>
<?php if ($_product->isSaleable()): ?>
    <?php
    $customCss = Mage::getStoreConfig('pricewaiter/appearance/display_custom_css');
    $helper = $this->_getHelper();

    $displayPhrase =  Mage::getStoreConfig('pricewaiter/appearance/display_phrase') ? 'button_mo' : 'button_nyp';
    $displaySize = Mage::getStoreConfig('pricewaiter/appearance/display_size') ? 'sm' : 'lg';
    $displayColor = Mage::getStoreConfig('pricewaiter/appearance/display_color');
    $displayHoverColor = Mage::getStoreConfig('pricewaiter/appearance/display_hover_color');
    $brand = $_product->getData('brand');
    $image = $_product->getImageUrl();
    if ($helper->isEnabledForStore()):
        ?>
        <script type="text/javascript">
            //<![CDATA[
            var PriceWaiterOptions = {
                <?php if ($helper->isButtonEnabled()): ?>
                enableButton: true,
                <?php else: ?>
                enableButton: false,
                <?php endif; ?>
                <?php if ($helper->isConversionToolsEnabled()): ?>
                enableConversionTools: true,
                <?php else: ?>
                enableConversionTools: false,
                <?php endif; ?>
                button: {
                    type: <?php echo json_encode($displayPhrase); ?>,
                    size: <?php echo json_encode($displaySize); ?>,
                    <?php if ($displayColor): ?>
                    color: <?php echo json_encode($displayColor); ?>,
                    <?php endif; ?>
                    <?php if ($displayHoverColor): ?>
                    hoverColor: <?php echo json_encode($displayHoverColor); ?>,
                    <?php endif; ?>
                },

                product: {
                <?php if ($brand): ?>
                    brand: <?php json_encode($brand); ?>,
                <?php endif; ?>
                    sku: <?php echo json_encode($_product->getSku()); ?>,
                    name: <?php echo json_encode($_product->getName()); ?>,
                    price: <?php echo json_encode($helper->getProductPrice($_product)); ?>,
                    <?php if ($image != ''): ?>
                    image: <?php echo json_encode($image); ?>
                    <?php endif; ?>
                }
            };

            var PriceWaiterRegularPrice = '<?php echo (float) $_product->getPrice(); ?>';
            var PriceWaiterProductType = '<?php echo $_product->getTypeId(); ?>';
            var PriceWaiterWidgetUrl = "<?php echo $helper->getWidgetUrl(); ?>";
            //]]>
        </script>
        <div class="name-your-price-widget"
             style='display: block; clear: both; padding-top: 10px; <?php echo $customCss; ?>'>
            <span id="pricewaiter"></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
