<?php
$enabled = $this->getIsEnabled();
$ctEnabled = $this->getIsConversionToolsEnabled();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">PriceWaiter Widget</h4>
    </div>
    <div class="fieldset fieldset-wide" id="group_pricewaiter">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>

                <tr>
                    <td class="label"><label for="group_pricewaiter_enabled">Enabled</label></td>
                    <td class="value">
                        <select id="group_pricewaiter_enabled" name="pricewaiter[enabled]" class=" select">
                            <option value="1" <?php if ($enabled): ?>selected="selected"<?php endif; ?>>Yes</option>
                            <option value="0" <?php if (!$enabled): ?>selected="selected"<?php endif; ?>>No</option>
                        </select>
                    </td>
                    <td class="scope-label">
                        <span class="nobr">[STORE VIEW]</span>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="group_pricewaiter_conversion_tools_enabled">Conversion Tools Enabled</label></td>
                    <td class="value">
                        <select id="group_pricewaiter_conversion_tools_enabled" name="pricewaiter[ct_enabled]" class=" select">
                            <option value="1" <?php if ($ctEnabled): ?>selected="selected"<?php endif; ?>>Yes</option>
                            <option value="0" <?php if (!$ctEnabled): ?>selected="selected"<?php endif; ?>>No</option>
                        </select>
                    </td>
                    <td class="scope-label">
                        <span class="nobr">[STORE VIEW]</span>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
