<?php

/**
 * Base for implementing test cases that work with a single simple product.
 */
abstract class AbstractSimpleProductTest extends PHPUnit_Framework_TestCase
{
    // Things we reference in the sample data set.
    public $SIMPLE_PRODUCT_SKU = 'hde012';
    public $SIMPLE_PRODUCT_ID = '399';
    public $SIMPLE_PRODUCT_PRICE = '150.00';

    /**
     * Parameters for a basic "Create deal" request.
     * @var null
     */
    public $createRequest = null;

    /**
     * The current date/time for test purposes.
     * @var string
     */
    public $now = '2016-03-05 12:12:12';

    private $_createdModels = array(
        'nypwidget/deal' => array(),
    );

    public function setUp()
    {
        $this->createRequest = array(
            'id' => 'SOMECREATEREQUEST',
            'api_key' => getenv('PRICEWAITER_API_KEY'),
            'version' => '2016-03-01',
            'body' => array(
                'id' => null, // Autogenerated if not specified
                'items' => array(
                    array(
                        'product' => array(
                            'sku' => $this->SIMPLE_PRODUCT_SKU,
                        ),
                        'quantity' => array(
                            'min' => 1,
                            'max' => 1,
                        ),
                        'amount_per_item' => array(
                            'cents' => 9999,
                            'value' => '99.99',
                        ),
                        'metadata' => array(
                            "_magento_product_type" => "simple",
                            "_magento_product_configuration" => http_build_query([
                                "form_key" => "aoeuaoeu9292",
                                "product" => $this->SIMPLE_PRODUCT_ID,
                            ]),
                        ),
                    )
                ),
                'coupon_code_prefix' => 'PW',
                "buyer" => array(
                    "id" => "1e9cfc2a-2bf8-4b78-9c7a-4fb31764e1e1",
                    "email" => "user@example.org",
                    "marketing_opt_in" => false,
                    "location" => array(
                        "postal_code" => "98225",
                        "country" => "US",
                    ),
                ),
            ),
        );

    }

    public function tearDown()
    {
        foreach($this->_createdModels as $model => $ids) {

            foreach($ids as $id) {

                $instance = Mage::getModel($model)->load($id);
                if ($instance) {
                    $instance->delete();
                }

            }
        }
    }

    /**
     * Creates an (unsaved) Deal model based on a "create" request.
     * @param  Array  $requestData
     * @param  String $now
     * @return PriceWaiter_NYPWidget_Model_Deal
     */
    public function createDeal(Array $requestData = array(), $now = null)
    {
        $requestData = array_merge($this->createRequest, $requestData);
        $now = $now === null ? $this->now : $now;

        if (empty($requestData['body']['id'])) {
            $requestData['body']['id'] = uniqid();
        }

        $request = new PriceWaiter_NYPWidget_Controller_Endpoint_Request(
            $requestData['id'],
            $requestData['api_key'],
            $requestData['version'],
            json_encode(
                $requestData['body']
            ),
            strtotime($now)
        );

        $deal = Mage::getModel('nypwidget/deal');
        $deal->processCreateRequest($request);

        $this->_createdModels['nypwidget/deal'][] = $deal->getDealId();

        $this->assertEquals($requestData['body']['id'], $deal->getDealId(), "deal_id is set on created deal");

        return $deal;
    }

}
