commands:
  N98\Magento\Command\Installer\InstallCommand:
    installation:
      defaults:
        timezone: 'America/New_York'
        currency: USD
        locale: en_US
        session_save: files
        admin_username: admin
        admin_firstname: John
        admin_lastname: Doe
        admin_password: password123
        admin_frontname: admin
        admin_email: john.doe@example.com
        encryption_key:
        use_rewrites: no
        use_secure: no
