commands:
  N98\Magento\Command\Installer\InstallCommand:
    installation:
      defaults:
        timezone: 'America/New_York'
        currency: USD
        locale: en_US
        session_save: files
        admin_username: admin
        admin_firstname: John
        admin_lastname: Doe
        admin_password: password123
        admin_frontname: admin
        admin_email: john.doe@example.com
        encryption_key:
        use_rewrites: no
        use_secure: no
    magento-packages:
      - name: magento-moved-ce-1.9.2.2
        version: 1.9.2.2
        dist:
          url: http://magento.com/downloads/assets/1.9.2.2/magento-1.9.2.2.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.9.1.0
    demo-data-packages:
      - name: sample-data-1.9.1.0
        version: 1.9.1.0
        dist:
          url: http://magento.com/downloads/assets/1.9.1.0/magento-sample-data-1.9.1.0.tar
          type: tar
